import type { ContextSnapshot, ExportedFile, Decision } from "@anchor/core";
import { fileTreeToString } from "@anchor/core";
import type { Exporter } from "./base.js";

export class CursorExporter implements Exporter {
  readonly name = "cursor";
  readonly description = "Export project context for Cursor IDE";
  readonly targetFiles = [".cursorrules", ".cursor/context.md"];

  export(snapshot: ContextSnapshot): ExportedFile[] {
    return [
      {
        path: ".cursorrules",
        content: this.buildCursorRules(snapshot),
      },
      {
        path: ".cursor/context.md",
        content: this.buildContextDoc(snapshot),
      },
    ];
  }

  private buildCursorRules(snapshot: ContextSnapshot): string {
    const lines: string[] = [];

    lines.push(`# Project: ${snapshot.summary}`);
    lines.push("");

    // Tech stack context
    if (snapshot.stack.frameworks.length > 0) {
      lines.push(`## Tech Stack`);
      lines.push(`- Frameworks: ${snapshot.stack.frameworks.join(", ")}`);
      if (snapshot.stack.languages.length > 0)
        lines.push(`- Languages: ${snapshot.stack.languages.join(", ")}`);
      if (snapshot.stack.buildTools.length > 0)
        lines.push(`- Build: ${snapshot.stack.buildTools.join(", ")}`);
      if (snapshot.stack.databases.length > 0)
        lines.push(`- Databases: ${snapshot.stack.databases.join(", ")}`);
      lines.push("");
    }

    // Active architectural decisions as rules
    const archDecisions = snapshot.decisions.filter(
      (d) => d.category === "architecture" || d.category === "technology"
    );
    if (archDecisions.length > 0) {
      lines.push(`## Architectural Decisions`);
      lines.push(
        `Follow these project decisions that have been made:`
      );
      lines.push("");
      for (const d of archDecisions) {
        lines.push(`### ${d.title}`);
        lines.push(d.description);
        if (d.reasoning) lines.push(`Reasoning: ${d.reasoning}`);
        lines.push("");
      }
    }

    // Other active decisions as guidelines
    const otherDecisions = snapshot.decisions.filter(
      (d) => d.category !== "architecture" && d.category !== "technology"
    );
    if (otherDecisions.length > 0) {
      lines.push(`## Project Guidelines`);
      for (const d of otherDecisions) {
        lines.push(`- **${d.title}**: ${d.description}`);
      }
      lines.push("");
    }

    // Notes
    if (snapshot.notes.length > 0) {
      lines.push(`## Notes`);
      for (const note of snapshot.notes) {
        lines.push(`- ${note}`);
      }
      lines.push("");
    }

    lines.push(`<!-- Generated by Anchor (https://yourcode.dev) -->`);

    return lines.join("\n");
  }

  private buildContextDoc(snapshot: ContextSnapshot): string {
    const lines: string[] = [];

    lines.push(`# Project Context`);
    lines.push(`> Generated by Anchor at ${snapshot.timestamp}`);
    lines.push("");

    lines.push(`## Summary`);
    lines.push(snapshot.summary);
    lines.push("");

    // File structure
    lines.push(`## File Structure`);
    lines.push("```");
    lines.push(fileTreeToString(snapshot.fileTree));
    lines.push("```");
    lines.push("");

    // Dependencies
    const depEntries = Object.entries(snapshot.dependencies);
    if (depEntries.length > 0) {
      lines.push(`## Key Dependencies`);
      for (const [name, version] of depEntries.slice(0, 20)) {
        lines.push(`- ${name}: ${version}`);
      }
      if (depEntries.length > 20) {
        lines.push(`- ... and ${depEntries.length - 20} more`);
      }
      lines.push("");
    }

    // Git info
    if (snapshot.gitInfo) {
      lines.push(`## Git Status`);
      lines.push(`- Branch: ${snapshot.gitInfo.branch}`);
      lines.push(`- Last commit: ${snapshot.gitInfo.lastCommitMessage} (${snapshot.gitInfo.lastCommit})`);
      if (snapshot.gitInfo.uncommittedChanges > 0) {
        lines.push(`- Uncommitted changes: ${snapshot.gitInfo.uncommittedChanges}`);
      }
      lines.push("");
    }

    // Full decision log
    if (snapshot.decisions.length > 0) {
      lines.push(`## Decision Log`);
      for (const d of snapshot.decisions) {
        lines.push(`### [${d.category.toUpperCase()}] ${d.title}`);
        lines.push(`*${d.timestamp}*`);
        lines.push("");
        lines.push(d.description);
        if (d.reasoning) {
          lines.push("");
          lines.push(`**Reasoning:** ${d.reasoning}`);
        }
        if (d.tags.length > 0) {
          lines.push(`**Tags:** ${d.tags.join(", ")}`);
        }
        lines.push("");
      }
    }

    return lines.join("\n");
  }
}
