import type { ContextSnapshot, ExportedFile } from "@anchor/core";
import { fileTreeToString } from "@anchor/core";
import type { Exporter } from "./base.js";

export class WindsurfExporter implements Exporter {
  readonly name = "windsurf";
  readonly description = "Export project context for Windsurf IDE";
  readonly targetFiles = [".windsurfrules"];

  export(snapshot: ContextSnapshot): ExportedFile[] {
    return [
      {
        path: ".windsurfrules",
        content: this.buildWindsurfRules(snapshot),
      },
    ];
  }

  private buildWindsurfRules(snapshot: ContextSnapshot): string {
    const lines: string[] = [];

    lines.push(`# Project Context`);
    lines.push(snapshot.summary);
    lines.push("");

    // Stack
    const s = snapshot.stack;
    if (s.frameworks.length > 0) {
      lines.push(`Tech: ${[...s.frameworks, ...s.languages].join(", ")}`);
      if (s.buildTools.length > 0) lines.push(`Build: ${s.buildTools.join(", ")}`);
      if (s.databases.length > 0) lines.push(`DB: ${s.databases.join(", ")}`);
      lines.push("");
    }

    // Decisions as concise rules
    if (snapshot.decisions.length > 0) {
      lines.push(`# Rules`);
      for (const d of snapshot.decisions) {
        lines.push(`- ${d.title}: ${d.description}`);
      }
      lines.push("");
    }

    // File overview
    lines.push(`# Structure`);
    lines.push("```");
    lines.push(fileTreeToString(snapshot.fileTree));
    lines.push("```");
    lines.push("");

    // Notes
    if (snapshot.notes.length > 0) {
      lines.push(`# Notes`);
      for (const note of snapshot.notes) {
        lines.push(`- ${note}`);
      }
      lines.push("");
    }

    lines.push(`<!-- Generated by Anchor · https://yourcode.dev -->`);
    return lines.join("\n");
  }
}
